// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTwkJWKCwggJf0INNtJQocjuV0jCTp118',
    appId: '1:143880492921:web:56a1bc65ef94adff77c1a8',
    messagingSenderId: '143880492921',
    projectId: 'todowwithfirebase',
    authDomain: 'todowwithfirebase.firebaseapp.com',
    databaseURL: 'https://todowwithfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'todowwithfirebase.appspot.com',
    measurementId: 'G-7SR6FXK2V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAG0kW7c3nd-A5XwjzwX10CNUCPzeCvJc',
    appId: '1:143880492921:android:5092e13705c00fa077c1a8',
    messagingSenderId: '143880492921',
    projectId: 'todowwithfirebase',
    databaseURL: 'https://todowwithfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'todowwithfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywAVzzfTTWniehJIbYs9U19xGqesHbp0',
    appId: '1:143880492921:ios:3287bee9966577fa77c1a8',
    messagingSenderId: '143880492921',
    projectId: 'todowwithfirebase',
    databaseURL: 'https://todowwithfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'todowwithfirebase.appspot.com',
    iosClientId: '143880492921-ms24uoc679g2qe99nv2q23sq9tggerm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywAVzzfTTWniehJIbYs9U19xGqesHbp0',
    appId: '1:143880492921:ios:3287bee9966577fa77c1a8',
    messagingSenderId: '143880492921',
    projectId: 'todowwithfirebase',
    databaseURL: 'https://todowwithfirebase-default-rtdb.firebaseio.com',
    storageBucket: 'todowwithfirebase.appspot.com',
    iosClientId: '143880492921-ms24uoc679g2qe99nv2q23sq9tggerm5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoWithFirebase',
  );
}
